# Dictionary of name options. Each type contains a list of 20 possible prefixes in a Pokemon's name.
prefix_dict = {"Normal": ["Me", "Pup", "Kanga", "Nor", "Ante", "Chip", "Fur", "Sap", "Ursa", "Neko", "Hound", "Pig", "Beige", "Bun", "Bov", "Lil", "Great", "Bear", "Ele", "Pure"],
             "Fire": ["Fla", "Infer", "Confla", "Em", "Pyro", "Lumin", "Tin", "Kin", "Igni", "Ex", "Char", "Oxi", "Incan", "Com", "Bon", "Camp", "Tor", "Warm", "Fieri", "Swel"],
             "Water": ["Wa", "Wave", "Hy", "Spla", "Aqua", "Dol", "Ocea", "An", "Su", "Sal", "Sea", "Noz", "Tor", "Tur", "Lob", "Land", "Or", "Atlan", "Ty", "Tidal"],
             "Electric": ["Vol", "Elec", "Cur", "Di", "Mo", "Mag", "Thun", "Light", "Max", "Resis", "Cir", "Amp", "Ampli", "Over", "Tran", "Pro", "Switch", "Bread", "Ac", "Pow"],
             "Grass": ["Synth", "For", "Tree", "Coco", "Flow", "Vege", "Wood", "Plant", "Chloro", "Leaf", "Bam", "Mush", "Musk", "Ever", "Palm", "Vine", "Bark", "Pet", "Brush", "Jun"],
             "Ice": ["Bliz", "Glac", "Fro", "Hail", "Ava", "Ice", "Frost", "Snow", "Arc", "Pol", "Aur", "Nar", "Pen", "Cryo", "Dry", "Icy", "Jack", "Win", "Sub", "Refridg"],
             "Fighting": ["Cham", "Kar", "Ju", "Kick", "Grap", "Tae", "Com", "Bat", "Vio", "Brawl", "Aggress", "Mili", "Su", "He", "Disci", "Chall", "Con", "Muay", "Wres", "Em"],
             "Poison": ["Poi", "Veno", "Scor", "Co", "Aci", "Toxi", "Poll", "Gar", "Neuro", "Muta", "Corro", "Nu", "Pesti", "Radio", "Bio", "Rattle", "Black", "Dart", "Octo", "Pro"],
             "Ground": ["Des", "Top", "Earth", "Can", "Cre", "Quick", "Mud", "Tec", "Bull", "Ex", "Un", "Quar", "Sho", "Dig", "Conti", "Terra", "Pla", "Sedi", "Crum", "Sand"],
             "Flying": ["Ea", "Fal", "Wind", "Tor", "Hurri", "Fea", "Spar", "Pidg", "Humming", "Heli", "Tou", "Ib", "Jet", "Goose", "Gale", "Zeph", "Peli", "Po", "Para", "Barred"],
             "Psychic": ["Psy", "Re", "Exper", "Esp", "Sooth", "Premo", "Hyp", "Medi", "Para", "Super", "Mys", "Gen", "For", "Occ", "Med", "Tele", "Mag", "Mu", "Sci", "Kine"],
             "Bug": ["Man", "Butter", "Spi", "Arach", "In", "Army", "Honey", "Mos", "Bee", "Crick", "Ter", "Silk", "Luna", "Lady", "Cic", "Hor", "Ant", "Drag", "Ento", "Paper"],
             "Rock": [],
             "Ghost": [],
             "Dragon": [],
             "Dark": [],
             "Steel": [],
             "Fairy": []
             }

# Dictionary of name options. Each type contains a list of 20 possible suffixes in a Pokemon's name.
suffix_dict = {"Normal": ["ow", "py", "roo", "mal", "lope", "munk", "coat", "ian", "major", "mata", "dog, "let", "tint", "ny", "ine", "peep", "dane", "claw", "phant", "clear"],
             "Fire": ["ming", "no", "gration", "ber", "maniac", "ous", "der", "dle", "tion", "plode", "coal", "dation", "descent", "bust", "fire", "flame", "rid", "burn", "heat", "ter"],
             "Water": ["ter", "pool", "dro", "shing", "tic", "phin", "nic", "chor", "shi", "mon", "horse", "zle", "toise", "tle", "ster", "lubber", "ca", "tis", "phoon", "wave"],
             "Electric": ["tage", "tric", "rent", "ode", "tor", "net", "der", "ning", "well", "tor", "cuit", "ere", "fier", "flow", "sister", "tron", "plate", "board", "decee", "er"],
             "Grass": ["esis", "est", "top", "nut", "er", "table", "works", "life", "phyll", "let", "boo", "room", "melon", "green", "tree", "whip", "wood", "al", "weed", "gle"],
             "Ice": ["zard", "ier", "zen", "fall", "lanche", "berg", "bite", "man", "tic", "ar", "ora", "whal", "guin", "genic", "ice", "cle", "frost", "ter", "zero", "erate"],
             "Fighting": ["pion", "ate", "do", "boxer, "pler", "kwando", "bat", "tle", "lence", "about", "ive", "tary", "mo", "roic", "ple", "enge", "test", "thai", "tle", "emay"],
             "Poison": ["son", "mous", "pion", "bra", "dic", "cant", "ute", "bage", "toxin", "gen", "sive", "clear", "cide", "active", "hazard", "snake", "widow", "frog", "pus", "tist"],
             "Ground": ["ert", "soil", "quake", "yon", "vasse", "sand", "slide", "tonic", "doze", "cavate", "earth", "ry", "vel", "dug", "nent", "firma", "net", "ment", "ble", "dune"],
             "Flying": ["gle", "con", "chill", "nado", "cane", "ther", "row", "eon", "bird", "copter", "can", "is", "plane", "gull", "storm", "yr", "can", "too", "keet", "owl"],
             "Psychic": ["chic", "search", "iment", "esp", "sayer", "nition", "nosis", "tate", "normal", "natural", "tic", "ius", "tune", "ult", "ium", "path", "ic", "tant", "fi", "sis"],
             "Bug": ["tis", "fly", "der", "nid", "sect", "ant", "bee", "qito", "tle", "et", "mite", "worm", "moth", "bug", "ada", "net", "lion", "onfly", "mology", "wasp"],
             "Rock": [],
             "Ghost": [],
             "Dragon": [],
             "Dark": [],
             "Steel": [],
             "Fairy": []
             }
